from __future__ import print_function
rtems_version = "7"
try:
    import rtems_waf.rtems as rtems
except:
    import sys
    print('error: no rtems_waf git submodule')
    sys.exit(1)

def init(ctx):
    rtems.init(ctx, version = rtems_version, long_commands = True)

def bsp_configure(conf, arch_bsp):
    pass

def options(opt):
    rtems.options(opt)

def configure(conf):
    rtems.configure(conf, bsp_configure = bsp_configure)

def build(bld):
    rtems.build(bld)
    bld(features='c cprogram', target='serial_example_1.exe', cflags='-g -O2', source=bld.path.ant_glob('*.c'))